
project_id = "bcqfzmqgiapmudulzfte"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.generate-course-outline]
verify_jwt = false

[functions.generate-module-content]
verify_jwt = false

[functions.generate-lecture-module]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-retry-quiz]
verify_jwt = false

[functions.generate-quiz-module]
verify_jwt = false

[vector]
enabled = false
