// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcqfzmqgiapmudulzfte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcWZ6bXFnaWFwbXVkdWx6ZnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTYzMDcsImV4cCI6MjA2MDM3MjMwN30.vDgSgbxrFglu-VLtoV0_vpHZT3nN2gUoqPuJrD3jGVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);